# Generated by Django 5.0.6 on 2024-09-18 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaccion_id', models.CharField(max_length=255)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.pedido')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('articulo_pedido_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.pedido')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.producto')),
            ],
            options={
                'db_table': 'articulos_pedido',
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('resena_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.producto')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.usuario')),
            ],
            options={
                'db_table': 'reseñas',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.usuario'),
        ),
    ]
