# Generated by Django 5.0.6 on 2024-09-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
